# Generated by Django 3.2 on 2023-05-15 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='celular',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nota',
            name='note',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='celular',
            field=models.IntegerField(),
        ),
    ]
